# Generated by Django 3.0.6 on 2020-05-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_home', '0002_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': [('can_answer', 'Can answer questions')]},
        ),
    ]
